"""new_skill

Revision ID: 2f33029b6e05
Revises: 18610d68b7ff
Create Date: 2025-10-04 17:28:41.644668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f33029b6e05'
down_revision: Union[str, Sequence[str], None] = '18610d68b7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('skill_game', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'skill_game')
    # ### end Alembic commands ###
