"""lifetime

Revision ID: b75720b61e36
Revises: eaa6b43949a0
Create Date: 2025-10-04 15:34:33.694444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75720b61e36'
down_revision: Union[str, Sequence[str], None] = 'eaa6b43949a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('life_time', sa.DateTime(), nullable=False, server_default=sa.text("NOW()")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'life_time')
    # ### end Alembic commands ###
