"""min_xp

Revision ID: cdfb5a3d584f
Revises: d30d0316ecdd
Create Date: 2025-10-04 18:02:18.072867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfb5a3d584f'
down_revision: Union[str, Sequence[str], None] = 'd30d0316ecdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type_min_xp_to_enter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type_min_xp_to_enter')
    # ### end Alembic commands ###
