"""min_xp

Revision ID: d30d0316ecdd
Revises: 2f33029b6e05
Create Date: 2025-10-04 17:44:02.223562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30d0316ecdd'
down_revision: Union[str, Sequence[str], None] = '2f33029b6e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('min_xp_to_enter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'min_xp_to_enter')
    # ### end Alembic commands ###
