"""xp

Revision ID: eaa6b43949a0
Revises: 25bce6daf5a4
Create Date: 2025-10-02 21:37:21.026820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa6b43949a0'
down_revision: Union[str, Sequence[str], None] = '25bce6daf5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('xp', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('xp_history', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('xp_history', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'xp')
    # ### end Alembic commands ###
