"""upgrade user model

Revision ID: f3dad3bf0869
Revises: 47d685937ccf
Create Date: 2025-07-14 19:42:05.470638

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3dad3bf0869"
down_revision: Union[str, Sequence[str], None] = "47d685937ccf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("disabled", sa.Boolean(), nullable=True))
    op.drop_constraint(op.f("users_password_hash_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_password_hash_key"),
        "users",
        ["password_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "disabled")
    # ### end Alembic commands ###
