"""upd

Revision ID: fcb8e31c0be9
Revises: 322f11e91f4b
Create Date: 2025-10-02 19:18:42.842345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb8e31c0be9'
down_revision: Union[str, Sequence[str], None] = '322f11e91f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_xp_history_user_id'), 'xp_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_history_user_id'), table_name='xp_history')
    # ### end Alembic commands ###
