"""tags_u

Revision ID: 16346d652516
Revises: f5ab829d9b0a
Create Date: 2025-08-28 16:47:20.538212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16346d652516'
down_revision: Union[str, Sequence[str], None] = 'f5ab829d9b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'tag_id')
    # ### end Alembic commands ###
