"""xp

Revision ID: 25bce6daf5a4
Revises: 06d9674545ba
Create Date: 2025-10-02 21:25:35.951614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bce6daf5a4'
down_revision: Union[str, Sequence[str], None] = '06d9674545ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('products', sa.Column('xp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'xp')
    # ### end Alembic commands ###
