"""ok

Revision ID: 495640bb24f8
Revises: 158b8fbb3690
Create Date: 2025-10-02 16:39:43.562837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495640bb24f8'
down_revision: Union[str, Sequence[str], None] = '158b8fbb3690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('products_search_idx'), table_name='products', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('products_search_idx'), 'products', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
