"""tags_u_1

Revision ID: e93c2d464b8b
Revises: 16346d652516
Create Date: 2025-08-28 17:27:22.953093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93c2d464b8b'
down_revision: Union[str, Sequence[str], None] = '16346d652516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tag_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('products_tag_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'tag_id')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.drop_column('tags', 'id')
    op.create_foreign_key(None, 'products', 'tags', ['tag_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tags_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.add_column('products', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_tag_id_fkey'), 'products', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'tag_name')
    # ### end Alembic commands ###
